# Generated by Django 5.2.2 on 2025-06-09 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('topics', models.ManyToManyField(related_name='articles', to='curation.interest')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('articles_included', models.ManyToManyField(related_name='newsletters', to='curation.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generation_date'],
            },
        ),
    ]
